name: It's my birthday

on:
  schedule:
    - cron: "0 3 13 6 *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3

      # Install rush
      - name: Install rush
        run: node common/scripts/install-run-rush.js install
      - run: rush install --no-link
      - run: rush link

      - run: cd tools/age && rushx start
      - run: cd tools/readme && rushx start

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
          message: "chore: update age in readme"
