name: Publish Packages

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true

      - name: Update npm
        run: npm install -g npm@latest

      - name: Run check
        run: pnpm check

      - name: Publish muuvmuuv package
        working-directory: packages/muuvmuuv
        run: npm publish

      # NOTE: I am not the owner sadly
      # - name: Publish marvin package
      #   working-directory: packages/marvin
      #   run: npm publish

      - name: Publish marvinheilemann package
        working-directory: packages/marvinheilemann
        run: npm publish
