name: Publish Packages

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Publish target'
        required: true
        default: 'both'
        type: choice
        options:
          - npm
          - github
          - both
  release:
    types: [published]

permissions:
  contents: read
  packages: write
  id-token: write  # Required for npm provenance and trusted publishing

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.20.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run checks
        run: pnpm check

      - name: Publish to NPM
        if: ${{ github.event.inputs.target == 'npm' || github.event.inputs.target == 'both' || github.event_name == 'release' }}
        run: pnpm publish:npm --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Configure GitHub Packages authentication
        if: ${{ github.event.inputs.target == 'github' || github.event.inputs.target == 'both' || github.event_name == 'release' }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@muuvmuuv:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Publish to GitHub Packages
        if: ${{ github.event.inputs.target == 'github' || github.event.inputs.target == 'both' || github.event_name == 'release' }}
        run: pnpm publish:github
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
